[workspace]

members = [
    "extern_type_callback_derive",
    "resource_main_macro",
    "altv_sdk",
    "resource_impl",
    "altv_module",
    "altvx",
    "example_resource",
    "logger",
]

[workspace.dependencies]
cxx = "1.0.91"
autocxx = "0.24.0"
anyhow = "1.0.69"
