[package]
name = "altv_module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
altv_sdk = { path = "../altv_sdk" }
core_module = { path = "../core_module" }
logger = { path = "../logger" }
paste = { workspace = true }
autocxx = { workspace = true }
lazy_static = { workspace = true }
libloading = "0.7.4"

[lib]
crate-type = ["cdylib"]
