[package]
name = "altv_module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
altv_sdk = { path = "../altv_sdk" }
alt = { path = "../alt" }
resource_api = { path = "../resource_api" }
cxx = "1.0"
dlopen = "0.1.8"
dlopen_derive = "0.1"
once_cell = "1.16.0"

[lib]
crate-type = ["cdylib"]
