[package]
name = "example_resource"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alt = { path = "../alt" }
tokio = { version = "1", features = ["full"] }
tokio-js-set-interval = "1.2.0"

[lib]
crate-type = ["cdylib"]
