name: Test

on:
  push:
    branches: "*"
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-22.04

    if: ${{ !startsWith(github.event.head_commit.message, 'release new version:') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Doc tests
        run: |
          cargo test --doc

      - name: Server Test
        env:
          ALTV_BRANCH: ${{ github.ref_name }}
        run: |
          cargo run --bin run_test

  # test-windows:
  #   runs-on: windows-2022

  #   if: ${{ !startsWith(github.event.head_commit.message, 'release new version:') }}

  #   steps:
  #     - name: Install winget
  #       uses: Cyberboss/install-winget@v1
  #     - name: Install latest LLVM (clang)
  #       shell: powershell
  #       run: |
  #         winget install LLVM.LLVM --accept-source-agreements --silent
  #     - name: Clang version
  #       run: |
  #         clang --version
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         submodules: recursive
          
  #     - name: Cache
  #       uses: actions/cache@v3
  #       with:
  #         path: |
  #           ~/.cargo/bin/
  #           ~/.cargo/registry/index/
  #           ~/.cargo/registry/cache/
  #           ~/.cargo/git/db/
  #           target/
  #         key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
  #     - name: Doc tests
  #       run: |
  #         cargo test --doc

  #     - name: Server Test
  #       env:
  #         ALTV_BRANCH: ${{ github.ref_name }}
  #       run: |
  #         cargo run --bin run_test
